- ts/private/ts_project.bzl
- ts/private/ts_validate_options.bzl
rules_ts is used only with rules_js
> cleanup: remove rules_nodejs interop code

- examples/simple/BUILD.bazel
- ts/private/ts_lib.bzl
Now that we rely on rules_js, sources are copied to the output tree so they are next to generated ones by the time typescript sees them. That means there's no problem giving TS a common rootDir between the two.
> Allow generated files mixed with sources

- ts/private/ts_project_options_validator.js
the program path was absolute, similar to rules_nodejs #3462
> make ts_options_validator output deterministc

- ts/private/ts_project.bzl
ts_project fails when it is placed at workspace root with `declaration=True` due to empty declaration dir argument.
> fix: set declaration dir to "." when it is empty

- docs/rules.md
- ts/defs.bzl
- ts/private/ts_validate_options.bzl
Otherwise give a better error that the user needs to set the tsconfig attribute.
Previously the error was
```
ERROR: /home/alexeagle/Projects/bazel-examples/next.js/lib/BUILD.bazel:3:11: Copying file lib/tsconfig.json failed: missing input file '//lib:tsconfig.json'
```
> refactor: only set tsconfig.json as the default if the file exists

- docs/rules.md
- ts/defs.bzl
- ts/private/ts_project_worker.js
Since `outDir`, `declarationDir`, and `rootDir` affects where a program writes, it is never safe to use the same instance of a program for different targets even if they share tsconfig.
tail of https://github.com/aspect-build/rules_ts/pull/41
> fix: use tsconfig, outDir, declarationDir, and rootDir in worker key

- e2e/worker/test.sh
- e2e/worker/trace/BUILD
- ts/private/ts_project_worker.js
Changes to worker mode
- Implements [typescript performance tracing](https://github.com/microsoft/TypeScript/wiki/Performance-Tracing) which is available in `4.1` and above in addition to performance timings. 
- Implements caching of  `typescript/lib` ASTs across workers so that cost is paid once for each worker
- Fixes #50 
New tracing API can be enabled per target
```starlark
ts_project(
name = "ts",
args = [
"--generateTrace",
"/absolute/path/to/workspace/traces"
]
)
```
`/absolute/path/to/workspace/traces` can be relative as well but in that case tsc will put traces into `bazel-bin/path/to/target/<relative_path>`.
> fix: handle option changes and implement default lib cache

- examples/extends_chain/main/BUILD.bazel
- ts/private/ts_config.bzl
Without the fix, the new 'config_dict' example failed with bad pathing computation, like
error TS5012: Cannot read file '/shared/cache/bazel/user_base/b7a032561a02207b8d9235ce01302e53/execroot/aspect_rules_ts/bazel-out/k8-fastbuild/bin/examples/extends_chain/main/fig.node.json'
fixes #60
> fix: relative path computation handles parent dir

- examples/out_dir/BUILD.bazel
- examples/out_dir/main.ts
- ts/private/ts_project.bzl
The default `declaration_dir` was already calculated up above taking `out_dir` into account.
I'm not sure if `examples` is really the best place to test this? 2/3 of those failed to build without this fix...
> fix: fix declaration file output with out_dir set

- examples/transpiler/BUILD.bazel
- ts/private/ts_project.bzl
This was accidentally dropped AFAICT in https://github.com/bazelbuild/rules_nodejs/commit/96d37b6eb88ed72d40654fec5f1a9055ba5ee5e7
> fix: re-enable error when no outputs configured

- ts/private/ts_project.bzl
> fix: give better error when ts_project should be js_library

- ts/private/ts_project_worker.js
- ts/test/BUILD.bazel
- ts/test/ts_project_worker.test.js
- Reduces the amount of tree walking tsc has to do when performing module resolution
- Improved reproducibility now that we create a virtual filesystem constructed with the `inputs` map bazel provides.
- Zero filesystem calls performed for `fileExists` `directoryExists` `readDirectory` `getDirectories`. Consequently, tsc performs less of other fs system calls given the limited view of the actual filesystem.
I'll perform some benchmarks to see how much we gained from this.
Closes #66
> perf: minimize the amount fs calls worker makes

- examples/module_ext/BUILD.bazel
- examples/module_ext/a.mts
- examples/module_ext/b.mjs
- examples/module_ext/c.cts
- examples/module_ext/d.cjs
- examples/module_ext/expected_outputs.txt
- examples/module_ext/tsconfig.json
- ts/private/ts_lib.bzl
The file extensions allow individual files run by node to override the `type` in `package.json`. 
Added in typescript 4.7: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#new-file-extensions
> feat: add support for .mts and .cts source files

- examples/BUILD.bazel
- examples/dts_lib/BUILD.bazel
- examples/dts_lib/importer.ts
- examples/dts_lib/index.ts
- examples/dts_lib/lib_types.d.ts
- examples/dts_lib/tsconfig.json
- examples/simple/BUILD.bazel
- examples/simple/foo.ts
A test for `ts_project` containing `.d.ts` source files and another `ts_project` importing via relative + named imports (`js_library` + linked `npm_package`).
It seems like this is not possible with rules_nodejs: https://github.com/bazelbuild/rules_nodejs/commit/7b42331ac0bfc962e58067f4f0ce7dea5ffa7148
> test: add example of ts_project .d.ts source

- ts/defs.bzl
- ts/repositories.bzl
1.0.0-rc.2 breaks since we needed the fixes in https://github.com/aspect-build/rules_js/pull/323 and https://github.com/aspect-build/rules_js/pull/324
> chore: update to aspect_rules_js to latest commit hash

- examples/dts_lib/BUILD.bazel
- examples/dts_lib/importer_linked.ts
- examples/dts_lib/importer_rel.ts
- examples/dts_lib/index.ts
- examples/dts_lib/lib_types_2.d.mts
- ts/private/ts_lib.bzl
- ts/private/ts_project.bzl
Update ts_project rule to include both .d.mts and .d.cts declaration
files in DeclarationInfo provider
Also add test within existing dts_lib example
> fix: add .d.mts/.d.cts in declaration info

- examples/simple/BUILD.bazel
- ts/private/ts_config.bzl
TypeScript will try to resolve paths as npm packages otherwise
Fixes #124
> fix: ensure extends paths are relative

- .bazelversion
- e2e/bzlmod/.bazelversion
- e2e/worker/.bazelversion
- e2e/workspace/.bazelversion
5.3.0 breaks e2e/bzlmod so we also pin the e2e tests to 5.2.0 in this PR
> chore: update to bazel 5.2.0

- .github/workflows/ci.yaml
Trying this one from a non-fork. I guess we probably don't need it everywhere so can just close for now though?
🤷
> ci: run PR workflow on main repo and not forks

- ts/private/ts_project_worker.js
This data was part of this error previously but was removed in https://github.com/aspect-build/rules_ts/pull/77
I'm not sure if that was intentional, but I found it very helpful to have the data when trying to understand what was going wrong in my migration. So just a thought to add it back?
> fix: add file info to error for `tsc` overreach

- ts/private/ts_lib.bzl
- ts/test/BUILD.bazel
Partner to https://github.com/bazelbuild/rules_nodejs/pull/3535, applying that fix here as well.
The issue is that when calculating the output, it's overzealously removing the root_dir matches. I'm happy to change this to be whatever we think is clearest, because right now it is a bit magic-number-y.
> fix: `ts_project` fails if `root_dir` used deep in source tree

- internal_deps.bzl
This is from the https://github.com/bazel-contrib/rules-template template but we don't seem to use it.
>  chore(deps): remove bazel-integration-testing 

- README.md
https://github.com/aspect-build/rules_ts/issues/127
It took me a while to figure out which flag (out of dozens) is causing failures when adopting rules_ts into an existing repo, thus I think it'd be better mentioned somewhere.
Feel free to change wording or mentioning `vfs`.
> docs: mention --worker_sandboxing incompatibility

- ts/private/ts_project_options_validator.js
I'm finding this a bit awkward to test because typescript is only fetched from `BUILD.typescript` which isn't really accessible from tests. But every test out there ensures it at least works with valid config, and I've tested the case this is catching manually. @thesayyn I don't understand how you tested workers with such minimal mocking of typescript?
> fix: validate preserveSymlinks tsconfig option is not set

- WORKSPACE
- examples/package.json
- examples/pnpm-lock.yaml
- examples/project_references/BUILD.bazel
- examples/project_references/README.md
- examples/project_references/app/BUILD.bazel
- examples/project_references/app/index.ts
- examples/project_references/app/tsconfig.json
- examples/project_references/lib_a/BUILD.bazel
- examples/project_references/lib_a/index.ts
- examples/project_references/lib_a/tsconfig-extended.json
- examples/project_references/lib_a/tsconfig.json
- examples/project_references/lib_b/BUILD.bazel
- examples/project_references/lib_b/index.spec.ts
- examples/project_references/lib_b/index.ts
- examples/project_references/lib_b/tsconfig-test.json
- examples/project_references/lib_b/tsconfig.json
- examples/project_references/tsconfig-base.json
- internal_deps.bzl
- ts/private/ts_project.bzl
We need to propagate the tsconfig.json file to composite project dependents as an input. This was in rules_nodejs but we lost it.
Also correct the pathing for the tsbuildinfo output, which hadn't been tested in rules_ts yet.
Copied the three composite projects from rules_nodejs tests, so we have that coverage now.
Fixes #163
> fix: allow composite projects

- ts/private/ts_config.bzl
- ts/private/ts_project.bzl
- ts/private/ts_validate_options.bzl
When we pass to copy_files_to_bin_actions, we're required to convert these to a list, which is too bad. I don't have a big repo handy to run a bazel dump to profile how much memory this actually saves, unlike the contribution to rules_nodejs this is based on: https://github.com/bazelbuild/rules_nodejs/pull/3431
Closes #177
> refactor: TsConfigInfo uses depsets

- ts/defs.bzl
CURRENT PR: Just validate to ensure nothing is invalid, tsconfig dict or not: https://github.com/aspect-build/rules_ts/pull/173/commits/0fa1c8f916309923c9adcef3a63430cb83aa9627
Ensure tsconfig dict() and ts_project attributes don't collide: https://github.com/aspect-build/rules_ts/commit/a510a3c29e52566ad6359bbd073dfec3dc3dad7d
> fix: validate tsconfig dictionary values

- docs/rules.md
- ts/defs.bzl
- ts/private/ts_validate_options.bzl
This came from rules_nodejs and isn't used in rules_ts.
> fix: remove unused validate_options(has_local_deps)

- e2e/worker/BUILD
- e2e/worker/composite/BUILD.bazel
- e2e/worker/composite/a/BUILD.bazel
- e2e/worker/composite/a/index.ts
- e2e/worker/composite/b/BUILD.bazel
- e2e/worker/composite/b/index.ts
- e2e/worker/composite/index.ts
- e2e/worker/composite/tsconfig.json
- e2e/worker/test.sh
- e2e/worker/trace/BUILD
- ts/private/ts_project_worker.js
> fix: .tsbuildinfo is not written in subsequent builds

- examples/declaration_dir/BUILD.bazel
- examples/declaration_dir/dir/lib.ts
- examples/declaration_dir/expected_outputs.txt
- examples/declaration_dir/tsconfig.json
- examples/declarationdir_with_value/dir/lib.ts
- examples/declarationdir_with_value/expected_outputs.txt
make the folder name match the typescript compiler option
> docs: cleanup declaration_dir example

- examples/custom_compiler/BUILD.bazel
- examples/custom_compiler/component.ng.html
- examples/custom_compiler/component.ts
- examples/custom_compiler/tsconfig.json
- examples/package.json
- examples/pnpm-lock.yaml
> docs: add custom compiler example

- .gitattributes
- README.md
- docs/rules.md
- docs/transpiler.md
- docs/tsconfig.md
- examples/path_mappings/BUILD.bazel
- examples/project_references/app/BUILD.bazel
- ts/defs.bzl
Having these on their own markdown pages makes it much easier to explain,
and the table view produced by default Stardoc is terrible at showing so much nested stuff.
> docs: improve readability: extract transpiler/tsconfig to standalone

- .bazelrc.common
- .bazelversion
- .github/workflows/ci.bazelrc
- .github/workflows/ci.yaml
Also adds bazelversion matrix axis so we continue to test bazel v5.3.2 on CI
> chore: update to Bazel 6.0.0rc1

- .github/workflows/ci.yaml
- e2e/worker/pnpm-lock.yaml
- e2e/worker/pnpm-workspace.yaml
- e2e/worker/test.sh
- e2e/worker/transitive_closure/BUILD.bazel
- e2e/worker/transitive_closure/index.ts
- e2e/worker/transitive_closure/package.json
- e2e/worker/transitive_closure/packages/a/BUILD
- e2e/worker/transitive_closure/packages/a/index.d.ts
- e2e/worker/transitive_closure/packages/a/index.js
- e2e/worker/transitive_closure/packages/a/package.json
- e2e/worker/transitive_closure/packages/b/BUILD
- e2e/worker/transitive_closure/packages/b/index.d.ts
- e2e/worker/transitive_closure/packages/b/index.js
- e2e/worker/transitive_closure/packages/b/package.json
- e2e/worker/tsconfig.json
- ts/private/ts_project_worker.js
- ts/test/ts_project_worker/fstree.test.js
> fix: remove /node_modules/. from ignored paths

- examples/package.json
- examples/pnpm-lock.yaml
- examples/tsconfig_external/BUILD.bazel
- examples/tsconfig_external/index.ts
- examples/tsconfig_external/tsconfig.json
- ts/private/ts_config.bzl
> test: assert external tsconfig is usable with workers

- docs/transpiler.md
- examples/transpiler/babel.bzl
- ts/defs.bzl
- ts/private/ts_lib.bzl
- ts/test/BUILD.bazel
- ts/test/mock_transpiler.bzl
- ts/test/transpiler_tests.bzl
The current transpiler which takes 3 arrays with aligning indexes is a bad API, and to fix #219 one of those arrays will no longer align with the other 2 making it unusable.
Proposed solution in this PR: https://github.com/aspect-build/rules_ts/issues/219#issuecomment-1309178614
This change makes the transpiler API simply `transpiler(srcs)`. Any additional information required should be added via `partial.make` such as `out_dir`, `source_map` etc. Often these extra params will be required in order to align with the `ts_project` attributes. A macro will almost always be ideal to configure the transpiler including things like aligning these attributes.
swc change to do its own output declarations: https://github.com/aspect-build/rules_swc/commit/f7169623c180bd55aac4f60bc11d879bb83d81d4 …
> fix: support non-file transpiler srcs

- .github/workflows/release.yml
Remove the "pre-release" config setting since we're now generated production ready releases
> chore: update GH actions release yaml

- e2e/worker_workspace/WORKSPACE
failure looked like
```
node_modules/.aspect_rules_js/@types+node@16.11.59/node_modules/@types/node/globals.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
```
I think maybe TS 4.9 is breaking the custom compiler we wrote for worker mode? If so that's pretty urgent to fix.
> ci: fix broken main

- examples/package.json
- examples/pnpm-lock.yaml
Cannot bump to typescript 4.9 yet because the angular example will complain since it require typescript < 4.9. In the future we could support multiple typescript versions in this repo for testing.
> chore: bump example package.json deps

- e2e/workspace/WORKSPACE
- e2e/workspace/package.json
It's usually better to keep the typescript version under Bazel synced with what you use outside.
Fixes #256
> doc: update snippet to suggest ts_version_from

- ts/test/BUILD.bazel
- ts/test/transpiler_tests.bzl
No functional changes; just moving all of the targets that the test_suite depends on into the .bzl so the code is much easier to follow.
> chore: cleanup transpiler_test_suite test

- examples/js_lib/BUILD.bazel
- examples/path_mappings/BUILD.bazel
- ts/private/ts_project.bzl
- ts/repositories.bzl
- ts/test/BUILD.bazel
- ts/test/ts_project_test.bzl
Fixes https://github.com/aspect-build/rules_ts/issues/253
BREAKING CHANGE
Sources and transitive source of deps will no longer be added as inputs to the ts_project tsc action. The previous behaviour sub-optimal and unintended as it leads to unnecessary cascading rebuilds when only `.js` files of deps changed. The intended behaviour of ts_project that only declarations are included as inputs to the tsc action.
> fix: fix cascading rebuilds

- e2e/worker/package.json
- e2e/worker/pnpm-lock.yaml
- e2e/worker/test.sh
- e2e/worker_workspace/test.sh
- examples/pnpm-lock.yaml
- ts/private/ts_project_worker.js
Reporting changes in random order causes tsc to call fstree functions when it's not in the final state and leads to hard failures. the safest way to do it is to report deletion first, creations second, and finally the changes.
example of a hard failing case;
```
/bazel-bin/node_modules/@types/node  -->  .store/@types+node+1.x/node_modules/@types/node
```
when version of `@types/node` changes from `1.x` to `2.x` the new symlink for `/bazel-bin/node_modules/@types/node` will be `.store/@types+node+2.x/node_modules/@types/node`.
given the example, 
if the worker reports the changes first, then tsc will try to determine the new path for `/bazel-bin/node_modules/@types/node` by making a realpath call. However, functions such as `fileExists`, `directoryExists` won't return the correct results …
> fix: report changes in deleted, created, changed order

- README.md
- docs/troubleshooting.md
- ts/defs.bzl
_API documentation_ link should be updated to https://docs.aspect.build/rules/aspect_rules_ts once the new site launches
> chore: fixup links for new docsite

- .github/workflows/workspace_snippet.sh
These two lines are no longer needed as of 1.2.0 release.
Fixes https://github.com/aspect-build/rules_ts/issues/296
I manually edited the 1.2.0 release notes as well
> chore: fixup bzlmod release snippet

- examples/BUILD.bazel
- examples/deps_lib_transpiler/BUILD.bazel
- examples/deps_lib_transpiler/b/BUILD.bazel
- examples/deps_lib_transpiler/b/index.ts
- examples/deps_lib_transpiler/importer_linked.ts
- examples/deps_lib_transpiler/importer_rel.ts
- examples/deps_lib_transpiler/index.ts
- examples/deps_lib_transpiler/tsconfig.json
- ts/defs.bzl
I'm seeing this at sourcegraph using a transpiler just like this. It seems to be when there is an indirect npm dependency? Or that's my guess at least, I haven't fully investigated that.
The test is the exact same as `deps_lib` but using babel as the transpiler and fails without the fix.
> fix: transitive dependency type checking with transpiler

- .bazelignore
- examples/linked_tsconfig/BUILD.bazel
- examples/linked_tsconfig/package.json
- examples/linked_tsconfig/tsconfig.json
- examples/linked_tsconfig_consumer/BUILD.bazel
- examples/linked_tsconfig_consumer/index.ts
- examples/linked_tsconfig_consumer/package.json
- examples/linked_tsconfig_consumer/tsconfig.json
- examples/pnpm-lock.yaml
- examples/pnpm-workspace.yaml
- ts/private/ts_config.bzl
- ts/private/ts_project.bzl
Fixes https://github.com/aspect-build/rules_ts/issues/271 although it looks like there is additional speed bump that `tsc` doesn't follow the symlinked to the virtual store location of its `extends` so transitive npm deps of an `extends` can't be resolved. I suspect this is easily reproducible outside of Bazel when `hoist = False` in `.npmrc`.
See comment left in `examples/linked_tsconfig_consumer/tsconfig.json` for more info: 
```
{
"//": "the hacky path below is required because while @lib/tsconfig/tsconfig.json _will_ resolve, tsc won't follow the symlink into the virtual store so the transitive npm dep of @lib/tsconfig on @tsconfig/node18/tsconfig.json won't be resolvable",
"extends": "../node_modules/.aspect_rules_js/@lib+tsconfig@0.0.0/node_modules/@lib/tsconfig/tsconfig.json"
}
``` …
> feat: add JsInfo provider to ts_config rule

- .github/workflows/ci.yaml
- e2e/external_dep/.bazelignore
- e2e/external_dep/.bazelrc
- e2e/external_dep/.bazelversion
- e2e/external_dep/BUILD
- e2e/external_dep/WORKSPACE
- e2e/external_dep/app/.bazelignore
- e2e/external_dep/app/.bazelrc
- e2e/external_dep/app/.bazelversion
- e2e/external_dep/app/BUILD
- e2e/external_dep/app/WORKSPACE
- e2e/external_dep/app/package.json
- e2e/external_dep/app/pnpm-lock.yaml
- e2e/external_dep/lib.ts
- e2e/external_dep/package.json
- e2e/external_dep/pnpm-lock.yaml
- e2e/external_dep/tsconfig.json
- ts/private/ts_project.bzl
- ts/private/ts_validate_options.bzl
Fixes #284.
`short_path` is not sufficient to handle external paths and we need to strip `ctx.bin_dir.path` instead. This updates the `ts_project()` rules as well as adds a regression test which triggers a `ts_project()` target to build from the context of an external workspace.
> fix: ts_project external workspace builds

- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- ts/repositories.bzl
This brings in a fix for worker mode with node 14: https://github.com/aspect-build/rules_js/pull/927
> chore: update to rules_js 1.20.3

- ts/defs.bzl
- ts/private/ts_config.bzl
A client couldn't have a ts project that depended on a `testonly` dep.
> fix: pass common args to write_tsconfig

- docs/rules.md
- e2e/test/common.bats
- examples/skip_lib_check/off/BUILD.bazel
- examples/skip_lib_check/off/source.ts
- examples/skip_lib_check/off/tsconfig.json
- examples/skip_lib_check/on/BUILD.bazel
- examples/skip_lib_check/on/source.ts
- examples/skip_lib_check/on/tsconfig.json
- examples/skip_lib_check/unspecified/BUILD.bazel
- examples/skip_lib_check/unspecified/source.ts
- examples/skip_lib_check/unspecified/tsconfig.json
- ts/defs.bzl
- ts/private/ts_lib.bzl
- ts/private/ts_project.bzl
closes #326
```
Benchmark 1: bazel build examples/skip_lib_check/unspecified
Time (abs ≡):         1.734 s               [User: 0.051 s, System: 0.060 s]
Benchmark 2: bazel build examples/skip_lib_check/on
Time (abs ≡):        737.8 ms               [User: 59.2 ms, System: 50.6 ms]
Benchmark 3: bazel build examples/skip_lib_check/off
Time (abs ≡):         1.180 s               [User: 0.049 s, System: 0.045 s]
Summary
'bazel build examples/skip_lib_check/on' ran
1.60 times faster than 'bazel build examples/skip_lib_check/off'
2.35 times faster than 'bazel build examples/skip_lib_check/unspecified'
```
> feat: introduce skip_lib_check attribute

- ts/BUILD.bazel
- ts/defs.bzl
Here's the DX of what the `select` failure message looks like, will be live for 2.0 under this proposal:
```
$ bazel build examples/simple:ts --strategy=TsProject=sandboxed -s
ERROR: /home/alexeagle/Projects/rules_ts/examples/simple/BUILD.bazel:9:11: configurable attribute "args" in //examples/simple:ts doesn't match this configuration: 
######## Required Typecheck Performance Selection ########
TypeScript's type-checking exposes a flag `--skipLibCheck`:
https://www.typescriptlang.org/tsconfig#skipLibCheck
Using this flag saves substantial time during type-checking.
Rather than doing a full check of all d.ts files, TypeScript will only type-check the code you
specifically refer to in your app's source code.
We recommend this for most rules_ts users.
HOWEVER this performance improvement …
```
> feat: skipLibCheck take 2

- examples/tsconfig_types/BUILD.bazel
- examples/tsconfig_types/index.ts
- examples/tsconfig_types/tsconfig.json
- examples/tsconfig_types/types/typings.d.ts
Just a basic example/test of `ts_config` deps. The `compilerOptions.types` having no `.d.ts` file extension was a surprise to me which I first assumed was a `ts_config` deps bug but this example shows it working.
> examples: add tsconfig types example

- ts/defs.bzl
- ts/private/ts_config.bzl
- ts/private/ts_lib.bzl
- ts/private/ts_project.bzl
This allows us to use the _out_paths machinery for json sources as well.
To achieve this, we add a resolve_json_module parameter to relevant methods in ts_lib (ts_lib is private so this is a backwards compatible change).
There are two small side-effects to this refactor:
- We use _lib.relative_to_package rather than a prefix removal.
- json inputs that are not sources and do not have an input / output collision are now declared.
> refactor: consider json a js source (if resolve_json_module)

- README.md
Fix https://github.com/aspect-build/rules_ts/issues/325
> docs: add links to bazel-examples in readme

- e2e/external_dep/WORKSPACE
- e2e/external_dep/app/WORKSPACE
- e2e/workspace/WORKSPACE
- ts/extensions.bzl
- ts/repositories.bzl
Fix https://github.com/aspect-build/rules_js/issues/817
WDYT of changing this in 2.0+? Could add it as an alias for now...
> refactor: rename LATEST_VERSION to LATEST_TYPESCRIPT_VERSION

- .github/workflows/ci.yaml
We'll introduce features like validation actions which are only in 6.
BREAKING CHANGE:
Users will likely be forced to upgrade to Bazel 6 in order to use rules_ts 2.0
---
> chore: drop support for Bazel 5

- ts/defs.bzl
- ts/private/ts_project.bzl
This makes the abstraction less breaking when you bazel query.
Fixes #360
BREAKING CHANGE:
Any bazel query expressions, aspect implementations, or other "leaky abstractions" that keyed on the kind of the underlying rule being "ts_project_rule" will need to be updated to the new name "ts_project".
---
on `main`
```
bazel query --output=label_kind examples/tsconfig_external
ts_project_rule rule //examples/tsconfig_external:tsconfig_external
```
with this change
```
bazel query --output=label_kind examples/tsconfig_external
ts_project …
```
> fix: ts_project macro creates same-named rule

- .bazelrc
- ts/BUILD.bazel
Previously this was an undiscoverable feature.
BREAKING CHANGE:
Users will be required to choose a setting. The error message tells them what to do.
---
> feat: ask users about skipLibCheck when upgrading to 2.0

- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/bzlmod/package.json
- ts/extensions.bzl
Bug in the sense that it should be in the bzlmod API since it is already in the WORKSPACE API.
---
> fix: add missing ts_version_from to bzlmod API

- ts/private/versions.bzl
Updates the mirrored TS versions to include 5.1.6.
---
- Suggested release notes are provided below:
Add Typescript versions 5.1.5 and 5.1.6 to the mirrored TS versions.
> feat: update mirrored TS versions

- .bcr/presubmit.yml
- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- ts/repositories.bzl
Windows fix. BCR should be green now for Windows with this change.
---
> chore: bump rules_js dep to 1.29.2 to pickup Windows fix

- ts/BUILD.typescript
`is_typescript_5_or_greater` is referenced from `ts_project` macro. Which means that the config_setting is referenced from non-internal user packages and has to be public. Currently bazel has default behavior where config_settings are considered public by default but some projects choose to opt-out of that legacy behavior. In such cases using TS 5+ is impossible at the moment. 
See config_setting visibility: https://bazel.build/concepts/visibility#config-setting-visibility 
---
- Suggested release notes are provided below: 
Fixes build errors for TS 5+ users who enale `--incompatible_config_setting_private_default_visibility` bazel flag.
Build …
> Make `is_typescript_5_or_greater` config_setting public

- ts/defs.bzl
- ts/private/ts_lib.bzl
- ts/private/ts_project.bzl
- ts/private/ts_validate_options.bzl
- ts/test/ts_project_test.bzl
Avoid blocking the critical path (typechecking actions) on the validation. Not sure if we have a minimum bazel version we want to support?
> Move TS config validation to validation output group

- .bazelrc.common
- WORKSPACE
- e2e/test/common.bats
- internal_deps.bzl
- ts/BUILD.bazel
- ts/private/options.bzl
- ts/private/ts_project.bzl
You can just add a line to .bazelrc to restore the 1.x behavior, but this is our chance to make you read our Public Service Announcement about how and why to use swc instead.
Fixes #349
The error message suggests buildozer commands to add a `transpiler` attribute to all ts_project rules.
> feat(2.0): force users to choose a transpiler

- ts/BUILD.bazel
- ts/private/options.bzl
- Suggested release notes are provided below:
`--define=VERBOSE_LOGS` no longer has an effect, use the `--@aspect_rules_ts//ts:verbose=true` flag instead
> chore(2.0): remove VERBOSE_LOGS env var

- docs/transpiler.md
- ts/private/options.bzl
This includes a section about the new flag in rules_js to avoid npm_package causing type-checks.
---
- Documentation (updates to documentation or READMEs)
None
> chore(docs): move transpiler migration instructions to markdown

- docs/BUILD.bazel
- internal_deps.bzl
- ts/BUILD.bazel
- ts/private/BUILD.bazel
- ts/private/maybe.bzl
- ts/repositories.bzl
It is a two-line implementation, so the redirection of an extra starlark file isn't worth it.
Technically non-breaking as it's private API, but doing this on 2.0 anyway.
---
> chore: remove maybe helper

- .aspect/workflows/terraform/workflows.tf
Should add terraform formatting to git hooks in a follow-up.
> chore: fixup terraform formatting

- WORKSPACE
- e2e/external_dep/WORKSPACE
- e2e/external_dep/app/WORKSPACE
- e2e/test/common.bats
- e2e/worker/WORKSPACE
- e2e/workspace/WORKSPACE
- ts/repositories.bzl
This requires calling rules_js_dependencies when called in WORKSPACE, which we had previously skipped. We also need to call the bazel_features_deps in cases that the bazel_features_globals repo gets referenced.
---
Technically this is breaking if you rely on rules_ts to provide your rules_js version, now you may need to setup bazel_features as well.
> chore: bump rules_js version

- .aspect/workflows/config.yaml
- MODULE.bazel
bzlmod doesn't work fully yet in the root repository. https://github.com/aspect-build/rules_ts/pull/424 is a start to fix it up but it is not yet finished.
this should fix the warming job at HEAD which is currently [red](https://github.com/aspect-build/rules_ts/actions/workflows/aspect-workflows-warming.yaml)
> chore: disable bzlmod on Aspect Workflows

- docs/transpiler.md
- ts/BUILD.bazel
It doesn't work with custom flags even in Bazel 6.3
Thanks @fmeum for confirming.
> fix: don't recommend bazelrc common verb

- examples/connect_node/BUILD.bazel
This was non-hermetic, it passed on my machine due to files copied into bazel-out, but then after a bazel clean I could reproduce #434
Fixes #434
> fix: add missing data dep

- .github/workflows/release_prep.sh
- ts/private/versions.bzl
We can use this at runtime to support features like checking for updates.
> feat: stamp our version into release

- ts/defs.bzl
Skylib build_test is a test rule with testonly dependencies. ts_project accepts kwargs and passes common ones through when expanding. The testonly attribute is no longer passed to build_test to prevent analysis errors.
---
https://github.com/aspect-build/rules_ts/issues/468
This is a minor bugfix to remove testonly when specifying kwargs on build_test as called by ts_project. 
Technically, this is visible to end-users but only expands functionality and allows target configurations that previously wouldn't build to now build.
This has been manually tested in the repo by modifying `//ts/test:transpile_filegroup` to take `testonly = False`, which breaks the build by causing `//ts/test:transpile_filegroup_typecheck_test` to fail during analysis.
It is …
> fix: ensure ts_project does not propagate testonly to build_test

- ts/defs.bzl
- ts/test/ts_project_test.bzl
This was an interesting one, I'm surprised we haven't seen it before. See https://bazel.build/rules/language#mutability
> fix: allow dict() tsconfig defined at analysis time

- e2e/workspace/WORKSPACE
Per #474 this helps to avoid some conflict with some other code which assumes that name.
Fixes #474
> refactor: suggest naming node toolchain 'nodejs'

- .github/workflows/ci.yaml
I'm chatting with Son about what changed in the remote executors so we can get it green again. In the meantime it's blocking PRs.
---
> ci: disable RBE for now

- docs/transpiler.md
- ts/BUILD.bazel
Reverts aspect-build/rules_ts#431
Bazel 6.4 included @fmeum fix for 'common'.
Fixes #524
> Revert "fix: don't recommend bazelrc common verb"

- .bazelrc
- .bazelrc.common
- examples/connect_node/tsconfig.json
The 'skipLibCheck=always' was added in https://github.com/aspect-build/rules_ts/pull/371 without any explanation of why we'd want that setting for rules_ts itself. This is a prefactor for the regression test of #516 - and in general we should be testing with the 'stricter' setting to make more assurance that the rules behave correctly.
---
> chore: enable lib checks

- .github/workflows/ci.bazelrc
- .github/workflows/ci.yaml
- e2e/external_dep/MODULE.bazel
- e2e/external_dep/app/MODULE.bazel
- ts/private/ts_proto_library.bzl
Revert #529 with fixes
Suspicious workarounds to avoid protobuf problems: non-hermeticity with protoc->glibc and something in C++ toolchain
> chore: re-enable RBE testing

- docs/repositories.md
- ts/extensions.bzl
- ts/private/npm_repositories.bzl
- ts/repositories.bzl
It hasn't resulted in anyone knowing that a rules_ts upgrade was available. The CDN traffic from this is the vast majority of what we are serving. We never decided to roll it out to any other rulesets, so I feel that the experiment has failed. I also never finished the server-side code that responds to the requests.
---
The `check_for_updates` attribute on repository rules is removed. If you had set `check_for_updates = False` you may simply remove it.
> chore: tear out check_for_updates feature

- ts/private/ts_lib.bzl
I think this is even in 5.1 and ok for rules_ts? https://github.com/bazelbuild/bazel/commit/50bb742fc35c04ab422a7ce723160b27d6900e6c
---
- Performance (a code change that improves performance)
> perf: use starlark string.removeprefix

- ts/private/ts_lib.bzl
- ts/private/ts_project.bzl
To catch issues that may otherwise result in hard to understand messages, especially `root_dir` where the rule output declarations are declared incorrectly causing a "not all outputs were created" error.
Close https://github.com/aspect-build/rules_ts/issues/551
---
> feat: add ts_project validation of root/out/typing_out dir options

- .github/workflows/aspect-workflows.yaml
- .github/workflows/ci.yaml
Tested this pattern in rules_jasmine. Already landed there.
Same as https://github.com/aspect-build/bazel-lib/pull/771.
> chore: fix GHA concurrency check to not apply to main branch

- .github/workflows/BUILD.bazel
- ts/BUILD.bazel
- ts/defs.bzl
- ts/private/BUILD.bazel
- ts/private/build_test.bzl
Fixes #567
workaround for https://github.com/bazelbuild/bazel-skylib/issues/480
---
> fix: typecheck_test depends on the .d.ts files

- .github/workflows/BUILD.bazel
I think this was broken in f5df58cf2f036c45901394e9305526e2a9e4f616.
> chore: fix buildifier error

- MODULE.bazel
- WORKSPACE
- e2e/bzlmod/.bazelrc
- e2e/bzlmod/MODULE.bazel
- internal_deps.bzl
- ts/private/ts_proto_library.bzl
See https://github.com/bazelbuild/rules_proto/discussions/213
---
It will cause bzlmod users to get rules_proto 6.0.0 in their resolved dependencies, which is technically breaking.
Note, we could add automated e2e testing for the `--noincompatible_enable_proto_toolchain_resolution` path as well - feels like overkill given that the conditional logic is all using upstream helpers
> feat: support incompatible_enable_proto_toolchain_resolution

- ts/private/ts_lib.bzl
A user may want to supply an npm package such as `//:node_modules/tsconfig` to `extends` attribute
> fix: don't limit extends on ts_project to only .json files

- MODULE.bazel
- e2e/worker/MODULE.bazel
- ts/repositories.bzl
bazel-lib 2.7.3 has a bad URL in coreutils for darwin x86
> chore: bump miminum dep to aspect_bazel_lib 2.7.6

- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/external_dep/MODULE.bazel
- e2e/external_dep/app/MODULE.bazel
- e2e/worker/MODULE.bazel
- ts/repositories.bzl
aspect_bazel_lib min bump goes along with rules_js bump in https://github.com/aspect-build/rules_js/pull/1763 to pick up fix for copy_to_directory that affects npm_package: https://github.com/aspect-build/bazel-lib/pull/857.
> chore: bump to rules_js 2.0.0-rc1 and minimum aspect_bazel_lib 2.7.7

- .bazeliskrc
- .bazelrc
- .github/workflows/ci.yaml
- MODULE.bazel
- WORKSPACE
- WORKSPACE.bzlmod
- docs/BUILD.bazel
- internal_deps.bzl
- tools/toolchains/BUILD.bazel
> refactor: enable protoc toolchains

- .aspect/workflows/bazelrc
- .github/workflows/ci.bazelrc
- .github/workflows/ci.yaml
Uncached test run: https://github.com/aspect-build/rules_ts/actions/runs/9293607630/job/25577138421?pr=612
> chore: switch to Aspect Workflows for RBE

- MODULE.bazel
- ts/repositories.bzl
Ensures users pick up https://github.com/bazelbuild/rules_nodejs/pull/3760 fix which is a footgun that should be avoided.
> chore: bump minimum rules_nodejs to 6.2.0

- docs/rules.md
- ts/defs.bzl
- ts/private/ts_validate_options.bzl
The 'validate_options' rule is no longer produced by our macro, so this is not a breaking change for most users. However the symbol was exported in the public API, so the next major release is our opportunity to remove it.
---
- Breaking change (forces users to change their own code or config): yes
- Suggested release notes appear below: yes
The `validate_options` rule has been removed. This was typically not used directly by users, instead they relied on the `ts_project` macro to create such a rule, which it stopped doing in a 2.x release (https://github.com/aspect-build/rules_ts/releases/tag/v2.1.1)
Any users who had an explicit reference to this public API symbol should remove it, and rely on validation actions instead.
- …
> chore: fix a TODO for 3.0.0

- e2e/external_dep/MODULE.bazel
We didn't mean to pick up LATEST by default.
Makes CI green again. I'll send a follow-up PR to update us to latest and deal with that breakage intentionally.
> fix: pin typescript version in e2e test

- MODULE.bazel
- e2e/worker/MODULE.bazel
- examples/package.json
- examples/pnpm-lock.yaml
- examples/resolve_json_module/BUILD.bazel
- examples/tsconfig_external/BUILD.bazel
- examples/tsconfig_external/tsconfig.json
5.5 doesn't work yet, so going to 5.4 as a stepping stone. This is the minimal changes to other dependencies needed to make it green
> chore(deps): upgrade TypeScript used by example

- examples/out_dir/BUILD.bazel
Tests I found hidden in a branch locally...
---
> test: verify outputs of examples/out_dir test

- ts/private/ts_project.bzl
> refactor: remove unnecessary JsInfo hasattr calls

- ts/test/ts_project_test.bzl
While refactoring rules_js this test was failing due to the element order changing.
---
> test: do not depend on depset.to_list order

- ts/private/ts_project.bzl
Reduce unnecessary and duplicate array loops and concatenating.
---
> perf: reduce array array operations

- ts/private/ts_project.bzl
This code is going to shuffle and moving this out is easier now. The condition should be the exact same.
---
> refactor: move transpiler_selection_required to main ts_project_rule block

- ts/private/ts_lib.bzl
This function becomes 2-3x faster, saving around 100ms of analysis time at Airtable
---
> perf: reduce use of join in _to_out_path

- ts/private/ts_lib.bzl
We don't need to look up the index of the `.` multiple times. Also flip the `allow_js` condition while I'm here, it's probably faster this way.
> perf: remove _replace_ext in lib.bzl

- ts/private/ts_config.bzl
The tsconfig is only generated within the BUILD directory and there is an assert that the `srcs` are all within that directory, so the relative file paths are easy to compute.
---
> perf: remove unnecessary tsconfig relative_file computation

- e2e/worker/package.json
- e2e/worker/pnpm-lock.yaml
- examples/connect_node/package.json
- examples/linked_lib/package.json
- examples/linked_pkg/package.json
- examples/linked_tsconfig_consumer/package.json
- examples/package.json
- examples/pnpm-lock.yaml
Upgrade the tsc version used in examples to 5.6 to include the new `noCheck` feature.
---
> test: update typescript to 5.6

- e2e/test/validation.bats
- ts/defs.bzl
- ts/private/ts_project.bzl
This way tsc is not forced to always run as a validation action in the background and instead invoked only when the `*_typecheck` test is run.
Currently this only effects the `noEmit` case.
In the future this will allow the `isolatedDeclarations` fast-path to avoid running type-checking at all unless `bazel test` is run. This way something such as `ibazel run //devserver` will not be blocked waiting for the validation action to run in the background.
---
> refactor: change typechecking validation action to output group

- ts/defs.bzl
This is a follow-up to #675 which made the `@npm_typescript` repository less special.
This replaces the (hopefully) last occurrence of this special name that cannot be changed by configuration.
Alternatives I considered:
- Expose the `is_typescript_5_or_greater` flag on the `ts_project` macro: Simplest option at first, but since it is only used for config validation, that would become nonsensical.
- Add a `npm_typescript_package` or `npm_typescript_repository` parameter that would allow overriding all places where `@npm_typescript//` is used by default: Would offer more functionality (e.g. worker config checking), but would also be more invasive.
---
The change might make an incorrect warning disappear.
- Breaking change …
> fix: do not rely on @npm_typescript if custom tsc is provided

- examples/no_emit/BUILD.bazel
- examples/transpiler/BUILD.bazel
- ts/private/ts_project.bzl
Now that `--noEmit` can be used to typecheck without any output files it can also be used when a custom transpiler is used along with no dts outputs.
---
> feat: support ts_project with transpiler and no declarations for type-checking

- e2e/external_dep/MODULE.bazel
- e2e/external_dep/WORKSPACE
- e2e/external_dep/app/MODULE.bazel
- e2e/external_dep/app/WORKSPACE
- e2e/workspace/WORKSPACE
> chore: upgrade bazel-lib in e2e tests for windows fix

- ts/defs.bzl
- ts/private/ts_project.bzl
- ts/private/ts_project_worker.js
I've successfully tested this on Airtable's code base. Memory usage can be a problem when typechecking a lot of targets. Something like what @alexeagle requested in https://github.com/bazelbuild/bazel/issues/12165#issuecomment-769207271 might be useful. I'm still playing around with `--experimental_total_worker_memory_limit_mb` and `--experimental_shrink_worker_pool` to see if they can prevent OOMs.
Also, I don't know why, but I have not encountered https://github.com/aspect-build/rules_ts/issues/361 and I don't believe any changes in this PR would have done anything to fix that issue.
> Support TypeScript workers with isolated declarations and custom TypeScript

- ts/BUILD.bazel
Likely an oversight: all other flags below are public.
We would like to alias this flag to hide the rules_ts dependency and cannot because of the visibility.
---
- Searched for relevant documentation and updated as needed: Doc update IMO unnecessary.
- Suggested release notes appear below: no
> fix: make `//ts:skipLibCheck` flag public

- ts/private/ts_project.bzl
To be more distinct in what the action is doing.
---
> feat: specify tsc outputs in action progress message

- e2e/external_dep/.bazelignore
- e2e/external_dep/BUILD
- e2e/external_dep/MODULE.bazel
- e2e/external_dep/WORKSPACE
- e2e/external_dep/sub_external/.bazelrc
- e2e/external_dep/sub_external/BUILD.bazel
- e2e/external_dep/sub_external/MODULE.bazel
- e2e/external_dep/sub_external/WORKSPACE
- e2e/external_dep/sub_external/sub-lib.ts
- e2e/external_dep/sub_external/subdir/BUILD.bazel
- e2e/external_dep/sub_external/subdir/sub-lib.ts
- e2e/external_dep/sub_external/subdir/tsconfig.json
- e2e/external_dep/sub_external/ts.bzl
- e2e/external_dep/sub_external/tsconfig.json
- ts/private/ts_config.bzl
This is a fix over the changes in https://github.com/aspect-build/rules_ts/pull/687.
New unit-tests
- Covered by existing test cases: partial
- New test cases added: added under `e2e` folder.
- Add a TS repo as an external repository. This should have a target that:
- is a `ts_project`
- inside a subfolder
- has `tsconfig` attribute set to a `dict`.
- build the `ts_project` target inside this external repository
> Ensuring package_prefix is correct for external workspaces

- examples/json_data/BUILD.bazel
- examples/resolve_json_module/BUILD.bazel
- ts/defs.bzl
I noticed `resolveJsonModule` is treated different then all the other tsconfig attributes which must be aligned between the macro and tsconfig where you can't depend on the tsconfig dict. This allows setting the value only in the tsconfig dict like any other compiler option.
---
> fix: support setting resolveJsonModule with inline ts_project(tsconfig)

- .bazelrc
- MODULE.bazel
- docs/proto.md
- docs/repositories.md
- docs/rules.md
- internal_deps.bzl
- ts/defs.bzl
This flag was flipped for Bazel 8. Need this for rules_ts rollout at a client.
> fix: support --incompatible_disallow_empty_glob

- examples/global_consumer/BUILD.bazel
- examples/global_consumer/index.ts
- examples/global_consumer/tsconfig_gen.json.expected
- examples/global_dts_generated_tsconfig/global.d.ts
- examples/global_dts_generated_tsconfig/index.ts
- examples/global_dts_generated_tsconfig/tsconfig_gen.json.expected
- ts/private/ts_config.bzl
Fix https://github.com/aspect-build/rules_ts/issues/727
---
> fix: ts_project declaration sources from other directories

- docs/transpiler.md
I think this should be removed in the next rules_js major release and we should always recommend `js_library` for local workspace projects. `npm_package` should only be used as a target for building ready-to-publish npm package.
---
- Suggested release notes appear below: no
> chore: remove docs and decprecate exclude_types_from_npm_packages

- ts/private/ts_proto_library.bzl
- ts/test/BUILD.bazel
- ts/test/ts_proto_library/BUILD.bazel
- ts/test/ts_proto_library/bar.proto
- ts/test/ts_proto_library/foo.proto
- ts/test/ts_proto_library_test.bzl
Fixes #670.
As described in #670, protoc splits the arguments to `--proto_path` and `--descriptor_set_in` using an OS-specific path-separator. On posix, this is `:`, but on Windows this is `;`. The protobuf library takes the approach for its bazel rules to join on `ctx.configuration.host_path_separator`, so I've taken the same approach here as well.
---
https://github.com/AchilleaResearch/rules_ts_667/tree/repro_670 demonstrates the fix as a patch. `bazel build //:foo_ts_pb` on Windows with and without the patch https://github.com/AchilleaResearch/rules_ts_667/blob/repro_670/MODULE.bazel#L47
> fix: join `--descriptor_set_in` with host path separator

- .github/workflows/release_prep.sh
The previous wording "with Bazel 6" is outdated and makes that option appear to be the "legacy old bazel 6" snippet.
---
> docs: change release notes to encourage bzlmod

- examples/assets/BUILD.bazel
- examples/assets/src/index-runtime.ts
- ts/private/ts_project.bzl
https://github.com/aspect-build/rules_ts/pull/533, in fixing the issue caused by https://github.com/aspect-build/rules_ts/pull/493, also omitted adding assets that shouldn't be copied to the `JsInfo` provider. As a result, downstream rules (such as `esbuild`) will fail to find the file because it never collected it.
---
Easiest way to repro this issue is to pipe the existing test cases into an `esbuild` bundle. The target should fail with `[plugin: bazel-sandbox] Could not resolve "./generated.json"`.
> ts_project: ensure assets get propagated

- ts/private/ts_config.bzl
- ts/private/ts_lib.bzl
I found this confusing, and now this avoids invoking `_is_typings_src` 2x for every single src within the `ts_config` rule.
---
> refactor: simplify tsconfig.json files computation

- ts/defs.bzl
- ts/private/ts_project.bzl
With isolated declarations in TypeScript, it's no longer necessarily the case that typechecking a project also causes all of its dependencies to be typechecked. Some people prefer/expect the previous behavior when running typechecking locally, so this PR exposes a test target that will always typecheck a project and its dependencies, regardless whether any of them have enabled the `isolated_typecheck` flag.
Works well in our codebase!
> feat: add transitive typecheck output group

- .github/workflows/ci.yaml
- e2e/test/common.bats
It seems github workflows upgrade node and the pnpm version being used no longer works with the latest node. I had the same problem locally.
---
> test: use specific node version for pnpm in bat-tests

- examples/extends_chain/main/BUILD.bazel
- ts/private/ts_project.bzl
- ts/private/ts_validate_options.bzl
- ts/test/BUILD.bazel
- ts/test/ts_config_test.bzl
- ts/test/ts_project_test.bzl
Transitive tsconfig files/dependencies are propagated as their own `TsConfigInfo` dependency tree. Those tsconfig files/dependencies should never be outputs of `ts_project`.
Close #754
---
- Suggested release notes appear below: no
Never include tsconfig related files and dependencies in `ts_project` outputs.
> fix: do not include tsconfig inputs in ts_project outputs

- ts/private/ts_config.bzl
The `JsInfo.[transitive_]sources` from `ts_config` should contain the sources required to compile, while `JsInfo.[transitive_]types` should contain any additional files required to type-check.
---
> refactor: move ts_config src to outputted JsInfo.sources

- ts/defs.bzl
- ts/private/ts_lib.bzl
- ts/private/ts_project_options_validator.js
- ts/private/ts_validate_options.bzl
- ts/test/ts_project_test.bzl
Close #644
--
- Searched for relevant documentation and updated as needed: N/A
- Suggested release notes appear below: Yes
Normalize `ts_project` `*_dir` attribute paths.
Validate any use of `root_dir` includes the `exclude: []` workaround for https://github.com/aspect-build/rules_ts/issues/644
Before the change any usage of a declaration_dir that starts with "./" was leading to an error, now if the path starts with "./" it is simply removed and the behavior is as if it was not added at all.
| declaration_dir | tsconfig declarationDir | Result | Message                                                                                  |
|------------------|-------------------------|--------|------- …
> fix: add tsconfig root_dir/exclude validation

- ts/defs.bzl
If this is not passed, the _types target will get the package's default visibility.
In out case, we have a package with a very restrictive visibility, but one of the targets (`ts_project`) in the package is  explicitly set to `public`. We want to depend on the `_types` target, but that is not visible due the default visibility.
NOTE: This is relevant only when an `dts` emitter is provided.
---
- Suggested release notes appear below: no
Create a target with a `dts` emitter. Ensure the `_types` target gets the same visibility of the main target.
> fix: ensure ts_project _types target has the right visibility

- ts/private/ts_project.bzl
This is a patch that we've had at Airtable for a while, but didn't get around to upstreaming until now.
Doubt this would be a visible change by most.
> Disallow remote cache with workers

- examples/assets/BUILD.bazel
- ts/private/ts_lib.bzl
Add support to `ts_project()` for `assets` that are generated directly into the `outDir`.
---
- Suggested release notes appear below: yes
Before this PR the `ts-root-out_outputs_test` fails because the `outDir` gets duplicated (`root-out/root-out`):
```
==================== Test output for //examples/assets:ts-root-out_outputs_test:
3c3
< examples/assets/root-out/metadata/generated_metadata.json
---
> examples/assets/root-out/root-out/metadata/generated_metadata.json
FAIL: files "examples/assets/_expected_ts-root-out_outputs_test.txt" and "examples/assets/_ts-root-out_outputs_test_outputs.txt" …
```
> Add support to `ts_project()` for `assets` that are generated directly into the `outDir`

- examples/extends_chain/main/BUILD.bazel
- examples/tsconfig_types/BUILD.bazel
- ts/private/ts_project.bzl
Fix #781
---
- Suggested release notes appear below: yes
Include tsconfig deps when invoking tsc even when `ts_project(isolated_typecheck)`.
> fix: isolated_typecheck and transitive tsconfig deps

- .github/workflows/BUILD.bazel
- .github/workflows/bazel6.bazelrc
- ts/private/ts_project.bzl
- ts/private/ts_proto_library.bzl
- ts/private/ts_validate_options.bzl
Aspect uses shell wrappers that invoke tools like `dirname` and `uname`. When the default shell env is not inherited, this prevents tools from being found on systems without a working fallback $PATH (like NixOS).
This might be incompatible with setting the `env` attribute, unless the bazel flag `--incompatible_merge_fixed_and_default_shell_env` is set on Bazel versions < 7.
See also: https://github.com/NixOS/nixpkgs/issues/289505
---
> always set 'use_default_shell_env' in ctx.actions.run

- ts/defs.bzl
When using the `alias` variant of the `_types` (dedicated dts_emitter) the target will not be given the provided `tags`, unlike all the other targets generated by this macro, including the `_types` when created using the `filegroup`.
---
no
`bazel query //:target_types --output=xml` will show that the `tags` attribute was set correctly.
> Ensuring the _types target (when alias) has the right tags

- .bazelignore
- .bazelrc
- .github/workflows/ci.yaml
- MODULE.bazel
- WORKSPACE.bzlmod
- docs/.bazelversion
- docs/BUILD.bazel
- docs/MODULE.bazel
- tools/toolchains/BUILD.bazel
- ts/BUILD.bazel
Simplifies the method of avoiding compile of protoc from source in root repository
Partially reverts #614
> refactor: move stardoc to docs submodule

- examples/dts_pkg-outDir/BUILD.bazel
- examples/dts_pkg-outDir/importer_linked.ts
- examples/dts_pkg-outDir/index.ts
- examples/dts_pkg-outDir/lib_types.d.ts
- examples/dts_pkg-outDir/lib_types_2.d.mts
- examples/dts_pkg-outDir/tsconfig.json
- examples/transpiler/BUILD.bazel
- examples/transpiler/babel.bzl
A similar change will be required in swc to handle `.d.ts` files, similar to what tsc and the updated babel test are doing.
> test: demonstrate issue with ts_project(transpiler) and .d.ts srcs

- docs/.bazelrc
- docs/BUILD.bazel
- docs/MODULE.bazel
follow-up to #792 
I made an incredibly simple GHA at https://github.com/alexeagle/stardoc-prebuilt to give the JAR file we need
> refactor: don't build protoc in docs either, it's the slowest CI step

- ts/defs.bzl
- ts/private/ts_lib.bzl
- ts/private/ts_project.bzl
- ts/test/mock_transpiler.bzl
> refactor: normalize root/out/declaration dir in macro

- examples/isolated_typecheck/backend/BUILD.bazel
- examples/isolated_typecheck/core/BUILD.bazel
- examples/isolated_typecheck/frontend/BUILD.bazel
- examples/no_emit/BUILD.bazel
- examples/transpiler/BUILD.bazel
- ts/defs.bzl
Fix #817
- Suggested release notes appear below: yes
Ensure tsc is run by a test for type-checking when `isolated_typecheck=True`
> fix: ensure typecheck test target is declared when isolated_typecheck=true

- .bcr/metadata.template.json
I think this is causing https://buildkite.com/bazel/bcr-presubmit/builds/15966#0197d709-2d0a-4aaf-8578-98d215a91843 because only [one of the Alex's](https://github.com/bazelbuild/bazel-central-registry/blob/5a2654cd2ec696ef6f3e1e3ae5c2116da33446ed/modules/aspect_rules_ts/metadata.json#L8) has the `github_user_id` being added on BCR.
- Manual testing; please provide instructions so we can reproduce: guess
> chore: dedupe alex in bcr metadata

- ts/extensions.bzl
- ts/private/npm_repositories.bzl
A lot of these have been unused since:
* https://github.com/aspect-build/rules_ts/commit/25b680f5e83206bb2545257e74b3cbc1962e2660#diff-c8fdc2b2b11999a0968314b1661a55d4dc8a010ac6c3b27c6ff5a741f5f98949L90-L91
* https://github.com/aspect-build/rules_ts/commit/ad69d9358f47fba10ae46b3e9d4661ec14aef5a3#diff-c8fdc2b2b11999a0968314b1661a55d4dc8a010ac6c3b27c6ff5a741f5f98949
> refactor: remove unused internal attributes

- MODULE.bazel
- ts/BUILD.bazel
- ts/defs.bzl
- ts/extensions.bzl
- ts/repositories.bzl
> chore: update tools_telemetry to 0.2.8
