aspect-build/rules_ts

ts/defs.bzl
=> fix: disable ts worker if custom tsc is provided

examples/output_group/BUILD.bazel, examples/output_group/index.d.ts_, examples/output_group/index.ts, examples/output_group/tsconfig.json
=> test: add case for types output_group

examples/declaration_only/BUILD.bazel, examples/declaration_only/a.d.ts_, examples/declaration_only/a.ts, examples/declaration_only/tsconfig.json
=> test: add case for declaration_only

examples/tsbuildinfo/BUILD.bazel, examples/tsbuildinfo/lib.ts, examples/tsbuildinfo/tsconfig.json, ts/private/ts_project_worker.js
=> fix: allow tsc worker read outputs

e2e/worker/BUILD, e2e/worker/package.json, ts/BUILD.typescript
=> fix: support package.json with type=module

examples/root_dirs/BUILD.bazel, examples/root_dirs/src/lib.ts, examples/root_dirs/src/spec.ts
I was trying to test this along with `rootDir: "src"` but that seems to fail even with plain tsc 🤷 
This test seems worth adding though?
=> test: test rootDirs + outDir

.github/workflows/ci.yaml, e2e/worker/main.ts, e2e/worker/test.sh, ts/private/ts_project_worker.js
=> fix: correctly invalidate failed lookups

ts/private/ts_project.bzl
=> docs: one more reason why ts_project could produce no output

.bazelrc, .bazelrc.common, .github/workflows/ci.bazelrc, .github/workflows/ci.yaml, e2e/bzlmod/.bazelrc, e2e/worker/.bazelrc, e2e/workspace/.bazelrc
The rules_ts version of https://github.com/aspect-build/rules_js/pull/400
=> chore: add CI on RBE

ts/private/ts_project_worker.js, ts/test/ts_project_worker.test.js
=> fix: check for dangling symlinks

examples/dts_lib/BUILD.bazel, examples/js_lib/BUILD.bazel, examples/path_mappings/BUILD.bazel, examples/path_mappings/foo.ts, examples/path_mappings/tsconfig.json
=> test: add path_mapping example

examples/deps_lib/BUILD.bazel, ts/private/ts_project_worker.js, ts/test/BUILD.bazel, ts/test/ts_project_worker/BUILD.bazel, ts/test/ts_project_worker/fstree.test.js, ts/test/ts_project_worker/mock.js, ts/test/ts_project_worker/oom.test.js
=> fix: prevent worker from running oom

examples/simple/BUILD.bazel, ts/private/ts_lib.bzl
=> fix(ts_lib): omit "." segments in path joining

examples/module_ext/BUILD.bazel, examples/module_ext/e.ts
=> docs: show example of different module outputs

.bazelrc.common, .github/workflows/ci.yaml, .gitignore, e2e/worker/.bazelrc, e2e/worker/test.sh, e2e/worker_workspace/.bazelrc, ts/private/ts_project_worker.js
=> fix: support --experimental_allow_unresolved_symlinks flag

docs/rules.md, docs/troubleshooting.md, ts/defs.bzl
Ported from rules_nodejs wiki and removed rootDirs stuff
=> docs: add troubleshooting guide

.github/workflows/ci.yaml, ts/private/npm_repositories.bzl, ts/private/ts_project_worker.js, ts/repositories.bzl
=> fix: update deps and fix worker tests

ts/private/ts_project_worker.js, ts/test/ts_project_worker/fstree.test.js, ts/test/ts_project_worker/oom.test.js
=> fix: take project rescaling into consideration

README.md
=> docs: clarify why --worker_sandboxing does not work

examples/global_dts_generated_tsconfig/BUILD.bazel, examples/global_dts_generated_tsconfig/global.d.ts, examples/global_dts_generated_tsconfig/index.ts, ts/private/ts_config.bzl
Fixes https://github.com/aspect-build/rules_ts/issues/204
=> fix: include declarations in files of generated tsconfig

e2e/test/common.bats, e2e/test/source_maps.bats, examples/package.json, examples/pnpm-lock.yaml, examples/source_map_support/BUILD.bazel, examples/source_map_support/defs.bzl, examples/source_map_support/stack-trace-support.js, examples/source_map_support/test/BUILD.bazel, examples/source_map_support/test/a.ts, examples/source_map_support/test/b.ts, ts/private/ts_project_worker.js, ts/test/ts_project_worker/oom.test.js
waiting for confirmation from John
=> fix: source maps generated incorrectly

e2e/external_dep/BUILD, e2e/external_dep/tsconfig.json, ts/private/ts_project.bzl
=> fix: composite external projects

ts/private/ts_project_worker.js, ts/test/ts_project_worker/oom.test.js
=> fix: remove the check for emit

ts/private/ts_project.bzl
Fix https://github.com/aspect-build/rules_ts/issues/278
=> feat: configure ts_project progress_message based on transpile/declaration config

e2e/bzlmod/BUILD, ts/defs.bzl
=> fix: dictionary tsconfig extends with bzlmod

docs/troubleshooting.md
There have been a couple issues related to this recently and we need some better docs explaining it. It's really a `rules_js` topic it's normally typescript errors that bring this up.
See:
https://github.com/aspect-build/rules_ts/issues/344
https://github.com/aspect-build/rules_ts/issues/356
=> docs: add troubleshooting docs about undeclared dependencies

ts/private/versions.bzl
=> Add TypeScript 5.1.3

ts/private/versions.bzl
Chore (any other change that doesn't affect source or test files, such as configuration)
=> Add tool version for TypeScript 5.1.5

.bazelrc.common, e2e/test/common.bats
I cherry-picked commits from main and it went red
=> chore: green up 2.x branch

ts/repositories.bzl
- Suggested release notes are provided below:
Replace usage of `load("@aspect_rules_ts//ts:repositories.bzl", "LATEST_VERSION")` with `LATEST_TYPESCRIPT_VERSION`
=> chore(2.0): remove LATEST_VERSION

ts/BUILD.bazel
- Documentation (updates to documentation or READMEs)
None
=> fix: instructions for bazelrc should vary on common

ts/private/ts_project.bzl
=> fix(transpiler): move the check for default_to_tsc_transpiler

.bazelversion, .github/workflows/ci.yaml
Lets us use the 'common' verb in bazelrc
---
=> chore: upgrade to bazel 6.3

WORKSPACE, docs/repositories.md, ts/private/npm_repositories.bzl, ts/repositories.bzl
Fixes #308 
---
Built with update to this repo
=> feat: read typescript version from resolved.json

docs/troubleshooting.md
---
- Documentation (updates to documentation or READMEs)
None
=> docs: put debug sections about worker mode together

.aspect/workflows/terraform/workflows.tf, .github/workflows/.aspect-workflows-reusable.yaml, .github/workflows/aspect-workflows-warming.yaml, .github/workflows/deps.bzl
=> chore: update to Aspect Workflows 5.7.0-rc10

docs/repositories.md, e2e/workspace/WORKSPACE, ts/extensions.bzl, ts/private/npm_repositories.bzl, ts/repositories.bzl
- Relevant documentation has been updated
Did a build and watched for traffic on the cloudflare endpoint
=> feat: add check_for_update

.aspect/workflows/terraform/workflows.tf
=> chore: bump remote cache size & shard count & turn on k8s observability

.github/workflows/aspect-workflows-warming.yaml
=> chore: fixup warming cron --- gha does not support timezone

.aspect/workflows/terraform/workflows.tf, .github/workflows/.aspect-workflows-reusable.yaml, .github/workflows/aspect-workflows-warming.yaml, .github/workflows/deps.bzl
=> chore: upgrade to Aspect Workflows 5.8.2

.gitattributes, .github/workflows/release_prep.sh, ts/private/versions.bzl
Makes it match bazelbuild/rules_proto#189
=> refactor: put 'git archive' config in .gitattributes

.github/workflows/mirror.yml, ts/private/mirror_versions.sh, ts/private/versions.bzl
Based on https://github.com/aspect-build/rules_lint/blob/main/.github/workflows/mirror.yml
---
Will manually run the workflow after it merges.
=> chore: add automation for TS version mirroring

.bcr/metadata.template.json
Better tagging and notifications for bcr releases.
=> chore: update bcr maintainers list

.github/workflows/release_prep.sh, MODULE.bazel, WORKSPACE, e2e/bzlmod/MODULE.bazel, ts/defs.bzl, ts/private/ts_config.bzl, ts/private/ts_project.bzl, ts/private/ts_proto_library.bzl, ts/repositories.bzl
Support bazel-lib 1.x and 2.x.
- Tested against bazel-lib 1.x and 2.x
=> feat: import toolchains to use for copy actions

MODULE.bazel, WORKSPACE.bzlmod, examples/source_map_support/defs.bzl
Prerequisite to https://github.com/aspect-build/rules_ts/issues/488.
=> chore: green up HEAD when run with --enable_bzlmod

.aspect/workflows/config.yaml, .aspect/workflows/terraform/workflows.tf, .github/workflows/aspect-workflows-delivery.yaml, docs/BUILD.bazel, docs/delivery.sh
Tested here https://github.com/aspect-build/rules_ts/actions/runs/7203812064/job/19624309853?pr=504
=> chore: enable workflows delivery on demostration target

.aspect/cli/config.yaml, .aspect/workflows/bazelrc, .aspect/workflows/config.yaml, .aspect/workflows/terraform/workflows.tf, .bazeliskrc, .bazelversion, .github/workflows/.aspect-workflows-reusable.yaml, .github/workflows/aspect-workflows-delivery.yaml, .github/workflows/aspect-workflows-warming.yaml, .github/workflows/deps.bzl
=> chore: upgrade to Aspect Workflows 5.9.0-rc.9

.aspect/workflows/config.yaml
Note, I'm expecting this one will expose the problem of no setup step to create the empty comment.
=> feat: enable code review comments

.github/workflows/ci.yaml, MODULE.bazel, WORKSPACE.bzlmod, e2e/external_dep/MODULE.bazel, e2e/external_dep/app/MODULE.bazel, e2e/external_dep/app/WORKSPACE.bzlmod, e2e/worker/MODULE.bazel
Closes https://github.com/aspect-build/rules_ts/issues/488.
=> chore: run bzlmod on ci

.bazelignore, examples/linked_empty_node_modules/BUILD.bazel, examples/linked_empty_node_modules/index.ts, examples/linked_empty_node_modules/package.json, examples/linked_empty_node_modules/tsconfig.json, examples/pnpm-lock.yaml, examples/pnpm-workspace.yaml
Ref https://github.com/aspect-build/rules_js/issues/918
Ref https://github.com/aspect-build/rules_js/pull/1513
=> test: add test of empty node_modules target

.bazeliskrc, .bazelversion, .github/workflows/ci.bazelrc, .github/workflows/ci.yaml, .gitignore, MODULE.bazel, e2e/test/3p_deps.bats, e2e/test/tracing_and_performance.bats, internal_deps.bzl, ts/BUILD.bazel, ts/private/BUILD.bazel, ts/private/is_bazel_7_or_greater.bzl
Pre-factor from https://github.com/aspect-build/rules_ts/pull/593
=> chore: bump to Bazel 7

e2e/external_dep/MODULE.bazel, e2e/worker/WORKSPACE
Pre-factor some cleanup from https://github.com/aspect-build/rules_ts/pull/593
=> chore: misc cleanup

ts/private/versions.bzl
Reverts aspect-build/rules_ts#630
=> Revert "Changes by create-pull-request action"

e2e/external_dep/MODULE.bazel
Reverts aspect-build/rules_ts#639
=> Revert "fix: pin typescript version in e2e test"

examples/linked/BUILD.bazel, examples/linked/index.ts, examples/linked/package.json, examples/linked_consumer/test_file_all_linked.js, examples/linked_consumer/test_pkg_deps_linked.js, examples/pnpm-lock.yaml
=> test: transitive ts_project npm: deps

examples/assets/tsconfig.json, examples/connect_node/tsconfig.json, examples/custom_compiler/tsconfig.json, examples/deps_lib/tsconfig.json, examples/deps_lib_transpiler/tsconfig.json, examples/dts_lib/tsconfig.json, examples/emit_declaration_only/tsconfig.json, examples/extends_chain/tsconfig.json, examples/linked/tsconfig.json, examples/linked_empty_node_modules/tsconfig.json, examples/linked_tsconfig_consumer/tsconfig.json, examples/output_group/tsconfig.json, examples/package.json, examples/path_mappings/tsconfig.json, examples/pnpm-lock.yaml, examples/project_references/lib_a/tsconfig.json, examples/project_references/tsconfig-base.json, examples/proto_grpc/tsconfig.json, examples/resolve_json_module/tsconfig.json, examples/root_dir/tsconfig.json, examples/simple/tsconfig.json, examples/ts_project_dep/a/tsconfig.json, examples/ts_project_dep/b/tsconfig.json, examples/tsbuildinfo/tsconfig.json, examples/tsconfig_external/tsconfig.json, examples/tsconfig_types/tsconfig.json
=> feat: upgrade examples to TS 5.5

ts/repositories.bzl
=> chore: upgrade rules_js to v2 rc7

.github/workflows/aspect-workflows-delivery.yaml, .github/workflows/aspect-workflows-warming.yaml
=> chore: upgrade to Aspect Workflows 5.10.11

MODULE.bazel, WORKSPACE, e2e/bzlmod/MODULE.bazel, e2e/external_dep/MODULE.bazel, e2e/external_dep/app/MODULE.bazel, e2e/worker/MODULE.bazel, internal_deps.bzl, ts/repositories.bzl
=> chore: update to rules_js 2.0.0

ts/private/ts_lib.bzl
=> perf: cleanup default ext handling in _replace_ext

ts/private/ts_lib.bzl
=> perf: remove duplicate path.removeprefix calls

ts/private/ts_project.bzl
Cleanup and potentially minor perf improvement.
---
=> refactor: replace 2-arg .add_all with .add

ts/private/ts_config.bzl
=> refactor: always replace __files__ var in tsconfig template

ts/defs.bzl, ts/private/ts_lib.bzl, ts/private/ts_project.bzl, ts/test/mock_transpiler.bzl
Minor var renaming and usage changes to clarify intentions.
Moving common code to util macro.
---
=> refactor: simplify ts_project macro conditional logic

.github/workflows/ci.yaml
Rolls out https://github.com/bazel-contrib/rules-template/pull/124
=> chore: adopt conclusion job for stable status check

.bazelignore, .prettierignore, examples/pnpm-lock.yaml, examples/pnpm-workspace.yaml, examples/resolve_json_module_esm/BUILD.bazel, examples/resolve_json_module_esm/index.mts, examples/resolve_json_module_esm/package.json, examples/resolve_json_module_esm/tsconfig.json
=> test: add resolve_json_module with esm imports of package.json

ts/private/build_test.bzl
See https://github.com/bazelbuild/bazel-skylib/blob/1.7.1/rules/build_test.bzl#L19-L33
---
=> fix: windows typecheck_test .sh vs .bat error

ts/private/ts_project.bzl
This kept confusing me, even though I wrote it 😅 
---
=> refactor: cleanup ts_project(isolated_typecheck) logic

.bazeliskrc, docs/performance.md
=> docs: add performance.md discussing transpilers and isolated_typecheck

ts/extensions.bzl
Fix https://github.com/aspect-build/rules_ts/issues/788
---
=> fix: watch ts_version_from for changes in bazel8+

ts/private/ts_project.bzl
=> refactor: do not re-copy_to_bin ts_project(srcs)

ts/private/npm_repositories.bzl
Prevents accidental re-use of cached versions that would otherwise be used purely based on the "integrity" value. E.g. someone forgot to update the integrity but the `ts_version` is already different.
=> fix: avoid accidental re-use of incorrect cached versions

.github/workflows/ci.yaml, e2e/bzlmod/MODULE.bazel
=> test: run e2e bzlmod test on windows ci

.aspect/workflows/config.yaml, e2e/smoke/WORKSPACE, e2e/test/3p_deps.bats, e2e/test/common.bats, e2e/test/diagnostics.bats, e2e/test/emit_cache.bats, e2e/test/invalidation.bats, e2e/test/isolated_modules.bats, e2e/test/source_maps.bats, e2e/test/strategy.bats, e2e/test/third_party_deps.bats, e2e/test/tracing_and_performance.bats, e2e/test/validation.bats
=> test: update bazel-lib in e2e/smoke

.aspect/bazelrc/correctness.bazelrc, .aspect/bazelrc/performance.bazelrc, .bazelrc, .github/workflows/BUILD.bazel, .github/workflows/bazel6.bazelrc, .github/workflows/bazel7.bazelrc, .github/workflows/bazel8.bazelrc, .github/workflows/ci.yaml, MODULE.bazel, docs/.bazelrc, e2e/smoke/MODULE.bazel, ts/repositories.bzl
=> chore: add bazel8 testing on ci

.aspect/workflows/config.yaml, .github/workflows/ci.yaml, MODULE.bazel, tools/preset.bazelrc
After this lands, I'll remove some GHA testing that overlaps.
=> chore: enable aspect workflows for more Bazel versions

README.md
=> docs: remove resolved known issues from README

MODULE.bazel
=> chore: upgrade aspect_tools_telemetry to 0.2.5
